modLoader="javafml"
loaderVersion="[31,)"
#issueTrackerURL="http://my.issue.tracker/"

[[mods]]
	modId="biospheres"
	version="${version}"
	displayName="Biospheres"
	credits="Inspiration and some concepts taken from previous Biosphere mods by Risugami, Wolferus__ and BrainSlugs83"
	authors="Harry Youd (harryyoud)"
	displayURL="https://github.com/harryyoud/biospheres"
	description='Biospheres mod for Minecraft, adding a new world type with large spheres, each containing a different biome.'

	# A URL to query for updates for this mod. See the JSON update specification <here>
	#updateJSONURL="http://myurl.me/" #optional

	# A file name (in the root of the mod JAR) containing a logo for display
	#logoFile="examplemod.png" #optional

	[[dependencies.biospheres]] #optional
	    modId="forge"
	    mandatory=true
	    versionRange="[31,)"
	    ordering="NONE"
	    side="BOTH"

	[[dependencies.biospheres]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.15.2]"
	    ordering="NONE"
	    side="BOTH"